# Generated by Django 4.2.14 on 2024-08-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField()),
                ('role', models.CharField(max_length=200)),
                ('technologies', models.JSONField()),
                ('location', models.JSONField()),
                ('company', models.CharField(max_length=200)),
                ('language', models.JSONField()),
                ('remote', models.BooleanField()),
            ],
        ),
    ]
