# Generated by Django 4.2.14 on 2024-08-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_job_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='link_to_apply',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
