# Generated by Django 4.2.14 on 2024-08-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_link_to_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full-time'), ('INTERNSHIP', 'Internship'), ('PART_TIME', 'Part-time')], default='FULL_TIME', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='technologies',
            field=models.JSONField(null=True),
        ),
    ]
