# Generated by Django 4.2.14 on 2024-09-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_role_alter_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='technologies',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
