# Generated by Django 4.2.14 on 2025-04-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_job_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='link_to_apply',
            field=models.URLField(max_length=1000),
        ),
    ]
