services:
  db:
    restart: always
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/  
    ports:
      - "5433:5432"
    
  web:
    build: .
    container_name: django
    command: ./scripts/web_start.sh
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  celery_worker:
    build: .
    command: celery -A thedevhunt worker -l info
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  celery_beat:
    build: .
    command: celery -A thedevhunt beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  flower:
    build: .
    command: celery -A thedevhunt flower --port=5555
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "5555:5555"
    volumes:
      - .:/app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: ["redis-server"]

volumes:
  postgres_data:
